import os

import database
from sqlalchemy import text


EXPECTED_TARGET = "staging-schema-test"

EXPECTED_COUNTS = {
    "students": 10000,
    "vendor_types": 7,
    "vendors": 124,
    "transactions": 335466,
    "users": 0,
    "context_events": 191,
}

NEW_TABLES = {
    "user_vendor_links",
    "notifications",
    "report_exports",
    "contextual_events",
}

USER_COLUMNS = {
    "full_name": "VARCHAR",
    "status": "VARCHAR",
    "token_hash": "VARCHAR",
    "token_expires_at": "TIMESTAMPTZ",
    "failed_login_attempts": "INTEGER NOT NULL DEFAULT 0",
    "locked": "BOOLEAN NOT NULL DEFAULT FALSE",
}


def stop(message):
    raise RuntimeError("MIGRATION STOPPED: " + message)


def get_tables(connection):
    return set(
        connection.execute(text("""
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_type = 'BASE TABLE'
        """)).scalars().all()
    )


def get_columns(connection, table):
    return set(
        connection.execute(text("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = :table
        """), {"table": table}).scalars().all()
    )


def get_counts(connection):
    return {
        table: connection.execute(
            text(f"SELECT COUNT(*) FROM public.{table}")
        ).scalar_one()
        for table in EXPECTED_COUNTS
    }


def migrate():
    url = database.engine.url

    expected_host = os.getenv("BYTEBITE_STAGING_DB_HOST")
    expected_database = os.getenv("BYTEBITE_STAGING_DATABASE")
    target = os.getenv("BYTEBITE_MIGRATION_TARGET")

    print("Checking migration target...")

    if target != EXPECTED_TARGET:
        stop("Target must be staging-schema-test.")

    if not expected_host or url.host != expected_host:
        stop("Database hostname does not match the verified staging host.")

    if not expected_database or url.database != expected_database:
        stop("Database name does not match the expected staging database.")

    print("Endpoint:", url.host)
    print("Database:", url.database)

    with database.engine.begin() as connection:
        actual_database = connection.execute(
            text("SELECT current_database()")
        ).scalar_one()

        if actual_database != expected_database:
            stop("Connected database does not match the expected database.")

        tables = get_tables(connection)

        required_tables = set(EXPECTED_COUNTS)

        missing = required_tables - tables
        if missing:
            stop(f"Missing original tables: {sorted(missing)}")

        existing_new_tables = NEW_TABLES & tables
        if existing_new_tables:
            stop(
                "Some new tables already exist. Review them before migrating: "
                + str(sorted(existing_new_tables))
            )

        if not {"user_id", "vendor_id"} <= get_columns(
            connection, "users"
        ):
            stop("The users table is missing user_id or vendor_id.")

        if "vendor_id" not in get_columns(connection, "vendors"):
            stop("The vendors table is missing vendor_id.")

        fk_exists = connection.execute(text("""
            SELECT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'users_vendor_id_fkey'
                  AND contype = 'f'
            )
        """)).scalar_one()

        if not fk_exists:
            stop("Expected existing users-to-vendors foreign key was not found.")

        before = get_counts(connection)
        print("Original row counts:", before)

        if before != EXPECTED_COUNTS:
            stop(
                "Row counts differ from the verified baseline. "
                "No migration was applied."
            )

        print("Adding users columns...")

        for column, definition in USER_COLUMNS.items():
            connection.execute(text(
                f"ALTER TABLE public.users "
                f"ADD COLUMN {column} {definition}"
            ))

        print("Creating user_vendor_links...")

        connection.execute(text("""
            CREATE TABLE public.user_vendor_links (
                user_id INTEGER NOT NULL,
                vendor_id INTEGER NOT NULL,
                PRIMARY KEY (user_id, vendor_id),
                CONSTRAINT user_vendor_links_user_fk
                    FOREIGN KEY (user_id)
                    REFERENCES public.users(user_id)
            )
        """))

        print("Creating notifications...")

        connection.execute(text("""
            CREATE TABLE public.notifications (
                notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
                user_id INTEGER NOT NULL,
                vendor_id INTEGER NOT NULL,
                message TEXT,
                trigger_type VARCHAR,
                is_read BOOLEAN NOT NULL DEFAULT FALSE,
                is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
                is_cleared BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT notifications_user_fk
                    FOREIGN KEY (user_id)
                    REFERENCES public.users(user_id)
            )
        """))

        print("Creating report_exports...")

        connection.execute(text("""
            CREATE TABLE public.report_exports (
                report_id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
                vendor_id INTEGER,
                generated_by_user_id INTEGER,
                report_type VARCHAR,
                period_start DATE,
                period_end DATE,
                generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT report_exports_user_fk
                    FOREIGN KEY (generated_by_user_id)
                    REFERENCES public.users(user_id)
            )
        """))

        print("Creating contextual_events...")

        connection.execute(text("""
            CREATE TABLE public.contextual_events (
                event_id INTEGER GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
                source_context_id TEXT UNIQUE,
                source_year SMALLINT,
                name TEXT NOT NULL,
                event_type VARCHAR NOT NULL,
                subcategory TEXT,
                start_date DATE NOT NULL,
                start_time TIME,
                end_date DATE NOT NULL,
                end_time TIME,
                all_day BOOLEAN,
                location TEXT,
                campus TEXT,
                faculty TEXT,
                scope TEXT,
                source VARCHAR NOT NULL,
                source_organisation TEXT,
                source_name TEXT,
                source_file TEXT,
                source_url TEXT,
                source_page TEXT,
                verification_status TEXT,
                notes TEXT,
                created_by_user_id INTEGER,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT contextual_events_user_fk
                    FOREIGN KEY (created_by_user_id)
                    REFERENCES public.users(user_id)
            )
        """))

        print("Verifying migration...")

        final_tables = get_tables(connection)

        if not NEW_TABLES <= final_tables:
            stop("One or more new tables are missing.")

        for column in USER_COLUMNS:
            if column not in get_columns(connection, "users"):
                stop(f"Missing users column: {column}")

        after = get_counts(connection)

        if after != before:
            stop(
                "An original table's row count changed. "
                "The transaction will be rolled back."
            )

        print("Original row counts preserved:", after)

    print("SUCCESS: Migration committed.")
    print("Original business tables were not dropped or reset.")


if __name__ == "__main__":
    migrate()